export { compileProject } from './compiler/compileProject.mjs';
export { deriveProjectCapabilities } from './projections/projectPresentation.mjs';
export { validateArchivePackage } from './validation/projectPackage.mjs';
export { verifySourceSet } from './validation/sourceSet.mjs';
export { assertCatalogDescriptor, assertMediaItem, validateCatalogDescriptor, validateMediaItem } from './catalog/model/catalogPackage.mjs';
export { normalizeMediaItem } from './catalog/normalize/normalizeMediaItem.mjs';
export { buildYtDlpDiscoveryArgs, createYouTubeCatalogProvider, normalizeYouTubeObservation, parseYtDlpJsonLines } from './catalog/providers/youtube/ytDlpProvider.mjs';
export { mergeMediaItems } from './catalog/sync/mergeCatalog.mjs';
export { classifyCatalog, matchesClassificationRule, validateClassification } from './catalog/classify/classifyCatalog.mjs';
export { renderCatalogStatusMarkdown, summarizeCatalog, validateCatalogData } from './catalog/status/catalogStatus.mjs';
export { buildCatalogRows, renderCatalogMarkdown } from './catalog/export/catalogExport.mjs';
export { normalizeCatalogQuery, queryCatalog, renderCatalogQueryMarkdown } from './catalog/query/queryCatalog.mjs';
export { buildProjectMaterializationPlan } from './catalog/materialize/materializeProject.mjs';
